### ISSUE TITLE
"For Loop" passed parameter does not split values by delimiter and pass the entire string to the “loop value” parameter

### ISSUE THREAD

**Issue by YoavLevinger** [Top-Q/jsystem#238]
If the scenario is passed with a maven -Dparameter, and the parameter is placed within the For - Loop list as ${parameter}, then the loop value is not split using the semicolon (';') delimeter and is passed as one string. sample:
-Dparameter = "55a12819-d884-4a44-bfc3-b464af7ccf98;7ab8a281-d7f4-4da7-b59a-d2280a4b2e22"

Environment details:
- version 6.1.01
- java version "1.7.0_17"
- OS: Windows 7(64)

Steps to reproduce:
- Create a simple scenario with a For loop.
- Set the list for loop input to be ${test.parameter}.
- Add to the JSystem "test.vm.params" the following value:
 "-Dtest.parameter=Sunday;Monday;Tuesday;Wednesday"
- Run the simple created scenario so it will iterate over the For loop.

**Comment by nirarmon** [comment]
fixed please see issue #241
