### ISSUE TITLE
${param} throws “java.lang.NumberFormatException: For input string: "${}" in an int input fields of a BB

### ISSUE THREAD

**Issue by YoavLevinger** [Top-Q/jsystem#239]
When using a BB with input type int and setting it to ${param}, the JSystem GUI throws “java.lang.NumberFormatException".

This is a regression from older JSystem version 6.0.01. all current scenarios receiving int, for example: port number as ${https.port.number} from the maven as a run parameter, fail to open in this JSystem version.

Environment details:
version 6.1.01
java version "1.7.0_17"
OS: Windows 7(64)

Steps to reproduce:
- Use a BB with int as an input field value.
- Set this input field to ${parameter}
- Save.

**Comment by SSgtMendel** [comment]
${scneario:<parameter>} is also broken; Most likely related to this issue.

version 6.1.02
Java 1.8.0_45
Win8.1x64

Steps to reproduce:

- Add building block to scenario
- Add input to building-block that uses scenario value ${scenario:testVariable}
- Set the value in the scenario parameters (ex: test_value_string)
- Attempt to save the scenario (error pops up)
- Attempt to run the scenario using the maven plugin (also fails)

**Comment by itaiag** [comment]
This is the result of a fix that was done for issue #214
