### ISSUE TITLE
JSystem 6.1.01 and Sut parameters value inside the scenario

### ISSUE THREAD

**Issue by silvermax70** [Top-Q/jsystem#252]
Dear all,

i used to read sut values from sut files inside a scenario as sut:Path till the 6.1.00 version.

Now, after the upgrade to the 6.1.01 i receive the following warning:
WARNING: Failed to collect data due to Csv file ${sut:S1A/OrdersIng/path}/${sut:S1A/OrdersIng/filename} is not exist.

Is there another way to cal the sut value from the sut file?

Thanks
Massimo

**Comment by itaiag** [comment]
This problem is no longer reproduced in version 6.1.04
