### ISSUE TITLE
DataDriven step doesn't work with JDK8

### ISSUE THREAD

**Issue by Rafimr** [Top-Q/jsystem#257]
Executing scenario with datadriven step doesn't work on JSystem 6.1.02 with JDK8

Steps to reproduce:
1) Install JSystem 6.1.02 with JDK8.
2) Create a new scenario with a datadriven step.
3) Run scenario.

**Comment by itaiag** [comment]
This is not reproduced on environment with:

* Oracle Java 1.8..0_77-b03 (64-Bit)
* JSystem 6.1.02
* Ubuntu 

The building blocks in the container were executed as the number of rows in the file and parameters were assigned correctly. 

To reopen the bug, please provide the CSV file that you are using and additional information about the behavior.
