### ISSUE TITLE
running multiple scenarios from pom

### ISSUE THREAD

**Issue by azimovMichael** [Top-Q/jsystem#277]
Hi, Im trying to run several scenarios from the pom.xml file,
but it just keep saying that the scenario is null.

this is how the interesting part of the pom.xml is looking:
`<configuration>	
	<xmlFile>myScenarios.xml</xmlFile>
</configuration>	`

since I haven't found any example\doc on how the pom should look I basically guessed that this is the way..
Am I right?

**Comment by itaiag** [comment]
Running multiple scenarios from the POM was not tested. In most cases the command line is used for this purpose as described in this [Wiki page](https://github.com/Top-Q/jsystem-docs/wiki/JSystem-Maven-Plugin).

If you still want to run it from the POM, I would suggest trying it like this:

```xml
<plugin>
    <groupId>org.jsystemtest</groupId>
    <artifactId>jsystem-maven-plugin</artifactId>
    <version>6.1.04</version>
    <executions>
        <execution>
            <phase>integration-test</phase>
            <goals>
                <goal>run</goal>    
            </goals>
            <id>runScenario</id>
            <configuration>
                <sut>default0.xml,default1.xml,default2.xml</sut>
                <scenario>scenarios/default0,scenarios/default1,scenarios/default2</scenario>
            </configuration>    
        </execution>
    </executions>
    <dependencies>
        <dependency>
            <groupId>org.jsystem</groupId>
            <artifactId>my-tests-proj</artifactId>
            <version>[0.0,]</version>
            <scope>runtime</scope>
        </dependency>
    </dependencies>
</plugin>
```

I never tried it, so let me know if it worked for you.

**Comment by azimovMichael** [comment]
I didn't try it, decided to use it from the cmd.
I believe you have a bug in the maven plugin, you added a validation to check that the scenario and sut parameters are not null, but if I want to use the multiple scenarios xml I only send the xmlFile parameter, so the other two are of course null..

**Comment by azimovMichael** [comment]
I'm "cheating" your code by sending some not important strings threw -Dscenario & -Dsut and the real multiple scenario xml thre the -DxmlFile..
