### ISSUE TITLE
Unfinished threads keep running in the background after switching to the next test of a scenario

### ISSUE THREAD

**Issue by ronyb** [Top-Q/jsystem#284]
In special cases, where we create new threads from within a JSystem test, and the test's main thread finishes execution before the threads it spawned had finished, the new threads keep running in the background after JSystem already started executing the next test in the scenario.

The spawned threads keep doing work and may have severe side effects on the execution of the subsequent scenario tests.

Here is a code example of such a case:

```
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;

import org.junit.Test;

import junit.framework.SystemTestCase4;

public class ExecutorServiceTest extends SystemTestCase4 {

	@Test
	public void executorServiceTest() throws Exception {
		
		ExecutorService executorService = Executors.newSingleThreadExecutor();
		
		// creating and running a new thread which takes 10 seconds to finish execution 
		executorService.submit(() -> {
			
			for (int i=0; i<10; i++) {
				
				report.report(Thread.currentThread().getName());
				
				try {
					TimeUnit.SECONDS.sleep(1);
				} catch (InterruptedException e) {
					e.printStackTrace();
				}
			}
		});
		
		executorService.shutdown();
		
		// This allows the main thread to wait for a maximum of 5 seconds for the executor thread to finish.
		// When 5 seconds are over, the main thread will finish, the JSystem test will be done, but the executor
		// thread will continue running in the background and its report messages will get appended to the HTML
		// report of the next test in the JSystem scenario
		
		executorService.awaitTermination(5, TimeUnit.SECONDS); 
	}
}
```

When executing the above test twice from the same JSystem scenario, these are the reports we get:

First test report:

17:18:34: pool-1-thread-1
17:18:35: pool-1-thread-1
17:18:36: pool-1-thread-1
17:18:37: pool-1-thread-1
17:18:38: pool-1-thread-1
17:18:39:Start time: Tue Nov 08 17:18:34 IST 2016
17:18:39:End time : Tue Nov 08 17:18:39 IST 2016
17:18:39:Test running time: 5 sec.
17:18:39: pool-1-thread-1

Second test report:

17:18:40: pool-2-thread-1
**17:18:40: pool-1-thread-1**
17:18:41: pool-2-thread-1
**17:18:41: pool-1-thread-1**
17:18:42: pool-2-thread-1
**17:18:42: pool-1-thread-1**
17:18:43: pool-2-thread-1
**17:18:43: pool-1-thread-1**
17:18:44: pool-2-thread-1
17:18:45:Start time: Tue Nov 08 17:18:40 IST 2016
17:18:45:End time : Tue Nov 08 17:18:45 IST 2016
17:18:45:Test running time: 5 sec.
17:18:45: pool-2-thread-1

The **bold** reports above (pool-1-thread-1) are coming from a thread that was created by the first test, and they are being written to the report of the second test.

**Comment by itaiag** [comment]
This is what threads are suppose to do. The *awaitTermination* does not close the thread. 

From the Oracle documentation:
*"Blocks until all tasks have completed execution after a shutdown request, or the timeout occurs, or the current thread is interrupted, whichever happens first."*

You can always give a larger wait time, but anyway, this is not a JSystem problem, this is the normal Java behavior.
