### ISSUE TITLE
Bean dialog  - References usage

### ISSUE THREAD

**Issue by nirlib** [Top-Q/jsystem#292]
When  references to file paths being used in bean dialog the input is saved without backslashes.
example : ${run:view}  = F:\views\r  - in bean dialog the value is F:viewsr

**Comment by itaiag** [comment]
The fix causes a regression. Strings that include backslash that are part of parameter provider (Generic or array), get an additional three backslashes every time the bean dialog is closed by the user.

**Steps to Reproduce**

Open building block with parameter provided that has a string field. Fill backslash in the input.

![before](https://user-images.githubusercontent.com/1835335/31373286-246531ca-ada2-11e7-8a23-d93101dd1607.PNG)
 
Click on the *OK* button and open again.

![after](https://user-images.githubusercontent.com/1835335/31373388-8df8889e-ada2-11e7-9745-cd80a0523e45.PNG)

**Comment by itaiag** [comment]
The fault is probably in the added code block in the **ObjectArrayParameterProvider** and in the **GenericObjectParameterProvider**:

```Java
		StringBuilder propertiesSb = new StringBuilder();
		for (String line : propertiesString.split("\\r?\\n")) {
			if (line.contains("\\") && !line.contains("\\:"))
				line = line.replace("\\", "\\\\");
			propertiesSb.append(line+"\r\n");
		}

```

**Comment by itaiag** [comment]
Backslashes are also added to spaces.
