### ISSUE TITLE
Bean Dialog - empty input

### ISSUE THREAD

**Issue by nirlib** [Top-Q/jsystem#293]
When field in bean dialog is not produced the value is null.
When field in bean dialog is produced and then deleted the value is empty string.
(for String - empty string,  for File - File object with empty string)

**Comment by itaiag** [comment]
One option for a fix is to edit the `LinkedHashMap<String, String> propertiesToMap(Properties properties)` in the `GenericObjectParameterProvider` class:

```Java
	private static LinkedHashMap<String, String> propertiesToMap(Properties properties){
		LinkedHashMap<String, String> map = new LinkedHashMap<String, String>();
		Set<Object> keys = properties.keySet();
		for(Object key: keys){
			map.put(key.toString(), properties.getProperty(key.toString()));
		}
		return map;
	}
```
In case the value of the property is empty, the property should not be added to the map at all.
