### ISSUE TITLE
missing dependency at Top-q nexsus

### ISSUE THREAD

**Issue by igivon** [Top-Q/jsystem#295]
When creating new Jsystem Test project ( 6.1.06-SNAPSHOT ), fail to resolve Dependency il.co.topq.difido:difido-reports-common:2.0.05-SNAPSHOT ( see attached ), Its missing from Top-Q Nexus

![capture 002](https://cloud.githubusercontent.com/assets/7386112/25851728/8ea40c24-34cf-11e7-942e-b377caf41d62.PNG)

**Comment by itaiag** [comment]
Snapshot version are not recommended for regular usage. 
Please select  a release version in your archetype.
