### ISSUE TITLE
Properties from the summary.properties files are read only at the start of the execution

### ISSUE THREAD

**Issue by ivgenis** [Top-Q/jsystem#307]
Hi,

Properties don’t appear correctly in the reporter.

Looks like summary.properties file is being read in the wrong place.

When running scenario at the first time and adding properties A,B,C to summary.properties, I don't see them in the reporter at the end of the run, this is what I see:
 
![dif](https://user-images.githubusercontent.com/23208378/30912544-ac3ba03c-a395-11e7-91d5-3c6373927af1.png)

After running scenario again on the same JSystem instance (summary.properties with “A,B,C” already exists at the beginning of the run), I will see “A,B,C” in the reporter, but won’t see the properties that were added to summary.properties during the current run.

**Comment by itaiag** [comment]
The summary properties are read only at the creation of the root element. We should change it to be read at the beginning or end of each test case (building block).
The change needs to be done in the `AbstractHtmlReporter` in the `startContainer` method:

```Java
	@Override
	public void startContainer(JTestContainer container) {
		log.fine("Recieved start containter event");
		if (firstTest) {
			firstTest = false;
			startRun();
		}
		ScenarioNode scenario = new ScenarioNode(ScenarioHelpers.removeScenarioHeader(container.getName()));
		if (container.isRoot()) {
			// We keep scenario history only for the root scenario;
			int numOfAppearances = getAndUpdateTestHistory(container.getName());
			if (numOfAppearances > 0) {
				scenario.setName(scenario.getName() + " (" + ++numOfAppearances + ")");
			}
			addScenarioProperties(scenario);
			execution.getLastMachine().addChild(scenario);
		} else {
			if (container instanceof AntForLoop) {
				scenario.setName(((AntForLoop) container).getTestName(0));
			} else if (container instanceof AntFlowControl) {
				scenario.setName(container.getTestName());
			}
			currentScenario.addChild(scenario);
		}
		currentScenario = scenario;
		writeExecution(execution);

	}
```
The `addScenarioProperties` call should not happen only if the scenario is root
