### ISSUE TITLE
Jsystem slowness without any Log - when remote server is down

### ISSUE THREAD

**Issue by igivon** [Top-Q/jsystem#308]
when difido remote server is down, it seems Jsystem as many retry to connect the server and scenario run is paused for a long time before it starts to run. in addition there is not notification/Log to indicated the slowness reason.

**Comment by itaiag** [comment]
When JSystem is configured to work with the Difido server it will try to connect to the server at the beginning of each execution. If the server is down, JSystem will log a message in the report and will disable the `RemoteHtmlReporter` until the end of the execution. It will then try to reconnect at the beginning of the next execution. 
The message in the console looks something like this:

```
WARNING: Failed to init jsystem.extensions.report.difido.RemoteHtmlReporter connection with host 'localhost:8080' due to Connection refused: connect
```
