### ISSUE TITLE
Generating Tests Project from maven archetype failed (no more supported ?) 

### ISSUE THREAD

**Issue by RomanGlaz** [Top-Q/jsystem#324]
Generating Tests Project from maven archetype failed (no more supported ?) 

jsystem version: 6.1.09
java version: 1.8.0_161
mvn version:  3.5.2
OS : WIN 10

i executed create project command:
mvn archetype:generate -DarchetypeCatalog=http://maven.top-q.co.il/content/groups/public/archetype-catalog.xml

and got this exception:

c:\Automation\projects\Cedex>mvn archetype:generate -DarchetypeCatalog=http://maven.top-q.co.il/content/groups/public/archetype-catalog.xml
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] parent.automation
[INFO] Utils
[INFO] Browser
[INFO] Restapi
[INFO] Cedex.tests
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building parent.automation 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] >>> maven-archetype-plugin:3.0.1:generate (default-cli) > generate-sources @ parent.automation >>>
[INFO]
[INFO] <<< maven-archetype-plugin:3.0.1:generate (default-cli) < generate-sources @ parent.automation <<<
[INFO]
[INFO]
[INFO] --- maven-archetype-plugin:3.0.1:generate (default-cli) @ parent.automation ---
[INFO] Generating project in Interactive mode
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] parent.automation .................................. FAILURE [  0.819 s]
[INFO] Utils .............................................. SKIPPED
[INFO] Browser ............................................ SKIPPED
[INFO] Restapi ............................................ SKIPPED
[INFO] Cedex.tests ........................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.418 s
[INFO] Finished at: 2018-03-18T15:55:40+02:00
[INFO] Final Memory: 15M/155M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:3.0.1:generate (default-cli) on project parent.automation: archetypeCatalog 'http://maven.top-q.co.il/content/groups/public/archetype-catalog.xml' is not supported anymore. Please read the plugin documentation for details. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

c:\Automation\projects\Cedex>

Does you change this ? You is the new way to create jsystem SO/Tests object

**Comment by igivon** [comment]
as a containment, you can try specify mvn plugin lower ver. for example start the command: 
mvn org.apache.maven.plugins:maven-archetype-plugin:2.4:generate......

**Comment by RomanGlaz** [comment]
Thanks , its worked for me . does it jsystem issue ? does Jsystem will fix it ?

**Comment by itaiag** [comment]
This is due to a security change in Maven archetype catalog. More details can be found in [Maven documentation](http://maven.apache.org/archetype/maven-archetype-plugin/archetype-repository.html) 

There are two things you can do.

1. As Iddan mentioned, downgrade the archetype version to 2.x. as shown in the [JSystem wiki page](https://github.com/Top-Q/jsystem-docs/wiki/Quick-Start-Guide#tests-project)
1. Set the remote repository in the `settings.xml` file
