### ISSUE TITLE
parameter: mandatoryFields in @TestProperties is always displays the mandatory parameter in red (even if its defined)

### ISSUE THREAD

**Issue by RomanGlaz** [Top-Q/jsystem#325]
parameter: mandatoryFields in @TestProperties is always displays the mandatory parameter in red (even if its defined)

os: Win10
java: 1.8.0_161
jsystem 6.1.09

see the test:
in the example below i defined a value to mandatoryParameter but in jsystem GUI its RED  .
``
package com.cedex.automation.tests;

import com.cedex.automation.tests.base.AbstractBrowserBaseTest;
import jsystem.framework.TestProperties;
import org.junit.Test;

public class BASICBASICTEST extends AbstractBrowserBaseTest {

    private int mandatoryParameter = 1;

    @Test
    @TestProperties(name = "TST: MANDATORY PARAM Test", paramsInclude = {"mandatoryParameter"}, mandatoryFields = {"mandatoryParameter"}, returnParam = {})
    public void mandatoryParameterTest() {

    }

    public int getMandatoryParameter() {
        return mandatoryParameter;
    }

    public void setMandatoryParameter(int mandatoryParameter) {
        this.mandatoryParameter = mandatoryParameter;
    }
``
![mandatoryparambug](https://user-images.githubusercontent.com/36363338/39512873-1c36212c-4dfb-11e8-91e4-07d3813290fe.jpg)

**Comment by itaiag** [comment]
The red color marks the user that this is a mandatory param no matter if value is set or not. In case there is no value, the test is set in red in the scenario tree (the left side) and in case the user tries to execute the scenario, a warning message will be displayed. 

In the bottom line, while the color selection could have been better, this is not a bug, but, really is, the feature.
