### ISSUE TITLE
Setting parameter in SUT after initialization doesn't update the parameter value properly 

### ISSUE THREAD

**Issue by lubshilk** [Top-Q/jsystem#333]
Hi,

We try to save a new value to a parameter listed in SUT. When we try to read the parameter value from code, the new value is provided. When we try to use referenced parameter to read the value, we receive the old value or exception

When application under test is installed on testers, virtual number is provided per tester. We try to save it in SO and use it in  following TCs

We have SUT file with nested objects:
```
<sut>
<dynamicPropGeneralInfo>
        <class>com.GeneralInfoSO.ToolsDynamicPropertiesGeneralInfoSO</class>
        <Testers index="0">
            <class>com.GeneralInfoSO.TestersUploadSO</class>
                 <TesterName>Tester1</TesterName>
                 <TesterVirtNumber>12345</TesterVirtNumber>
      </Testers>
        <Testers index="1">
            <class>com.GeneralInfoSO.TestersUploadSO</class>
                 <TesterName>Tester2</TesterName>
                 <TesterVirtNumber/>
     </Testers>
</dynamicPropGeneralInfo>
</sut>
```
Code:
ToolsDynamicPropertiesGeneralInfoSO class

```
package com.cellact.GeneralInfoSO;
import jsystem.framework.system.SystemObjectImpl;
import com.cellact.GeneralInfoSO.TestersUploadSO;
public class ToolsDynamicPropertiesGeneralInfoSO extends SystemObjectImpl {
    private TestersUploadSO[] Testers;

    public void init() throws Exception {
        super.init();
    }
    public void close(){
        super.close();
    }
    
    public String getTesterNameByIndex(int index){
		return Testers[index].getTesterName();
	}
  public String getTesterVirtNumberByIndex(int index){
		return Testers[index].getTesterVirtNumber();
	}
  public void setTesterVirtNumberByIndex(int index, String virtNumber){
		Testers[index].setTesterVirtNumber(virtNumber);
	}
}
```
TestersUploadSO class:
```
package com.cellact.GeneralInfoSO;
import jsystem.framework.system.SystemObjectImpl;
public class TestersUploadSO extends SystemObjectImpl {
    private String TesterName = "";
    private String TesterVirtNumber = "";

    public void init() throws Exception {
        super.init();
    }
    public void close(){
        super.close();
    }
    
    public String getTesterName(){
		return TesterName;
	}
    public void setTesterName(String name){
		TesterName = name;
	}
   public String getTesterVirtNumber(){
		return TesterVirtNumber;
	}
  public void setTesterVirtNumber(String number){
		TesterVirtNumber = number;
	}
}
```
Test case that installs application on testers updates the virtual number:
 part of relevant code:
```
public class InstallRegister extends SystemTestCase4 {
  private ToolsDynamicPropertiesGeneralInfoSO GeneralInfo;
  @Before
  public void setUp() throws Exception {
      GeneralInfo = (ToolsDynamicPropertiesGeneralInfoSO) system
				.getSystemObject("dynamicPropGeneralInfo");
  }
  @TestProperties(name = "Re-installation test")
   public void ApplicationInstallationRegistration() throws Exception {
        //here installation and registration code returning virtual number
       String virtNumber = installApp();
       //setting virtual number in SO
      GeneralInfo.setTesterVirtNumberByInd(testerIndex, secondNum);
 }
```
If in the next test we try to retrieve the value programmatically:
_expectedSecNumVal = GeneralInfo.getTesterVirtNumberByInd(testerIndex);_
expectedSecNumVal contain updated value (as expected)

But when we try to use reference for parameter in other TC as 
![image](https://user-images.githubusercontent.com/20837714/43898081-da18fb22-9be6-11e8-9112-f6b286e3094d.png)
- if a value was set in SUT (as for Tester1) the old value received
- if a value was not set in SUT (as for Tester2) exception is thrown:
 _Reference syntax is incorrect! tried to set value ${sut:dynamicPropGeneralInfo/Testers[@index='0']/TesterVirtNumber} to property selendroidTester Reference= ${sut:dynamicPropGeneralInfo/Testers[@index='0']/TesterVirtNumber}
java.lang.Exception: Object was not found: sut/dynamicPropGeneralInfo/Testers[@index='0']/TesterVirtNumber/text()
at jsystem.framework.sut.SutImpl.getValue(SutImpl.java:141)_

Tried to provide maximum information
Let me know if more information is needed
Thanks

**Comment by itaiag** [comment]
Hi. 
You can see the SUT as the **initial state** of the system objects. When you change the state of the SOs during execution, the state is not saved in the SUT file but only in the in memory object. 

The SUT file can be changed **only**  by editing the file and not by settings the values programmatically.  

If you want the virtual number to be accessed from the code and from the runner by using a reference, you will need to use another approach. 
For example, you can use the JSystem run properties. 
Setting values:

```Java
RunProperties.getInstance().setRunProperty("TesterVirtNumber", "1234");
```
Reading the value from the runner can be done using reference from the following type:

````
${run:TesterVirtNumber}
````

**Comment by lubshilk** [comment]
Thank you for the fast reply and suggestion.
The problem with RunProperty here - we use the same TC for installing application and receiving virtual number on few testers in the same scenario (BTW, this is why we cannot use returnedParam as well )
Hmmm, how to overcome the problem...
Pity, we cannot use SO, it is very useful programmatically...

**Comment by itaiag** [comment]
There are a number of other ways that I can think about, but I don't think this is the best forum for discussing it. 
If you wish, feel free to continue this discussion via my mail at **itai.agmon@top-q.co.il**
