### ISSUE TITLE
'Pause Before This Item' button is not found in JSystem version 6.1.10

### ISSUE THREAD

**Issue by ivgenis** [Top-Q/jsystem#337]
Steps to reproduce:
1. Open scenario in JSystem
2. Right click on any test

**Expected Result - version 6.1.09**

![pausebutton](https://user-images.githubusercontent.com/23208378/44393658-fa8e0680-a53d-11e8-95f6-cbf14ce4210a.png)

**Actual Result - version 6.1.10**

![nopausebutton](https://user-images.githubusercontent.com/23208378/44393694-11345d80-a53e-11e8-9140-1262f1e0bf0c.png)

**Comment by itaiag** [comment]
Is it safe to assume that you did not add the 'pause before building block' plugin?

**Comment by ivgenis** [comment]
I checked with whom added 6.1.09 here and you are right. Sorry for the mistake.
