### ISSUE TITLE
jSystem is not working with Maven versions 3.8.1+

### ISSUE THREAD

**Issue by omri-ratson** [Top-Q/jsystem#371]
From Maven version 3.8.1 and above, Apache decided to block repositories that are not secured (HTTP instead of HTTPS).

I tested our project with the latest version 3.8.6 and I got the following error:
![jsystem-issue](https://user-images.githubusercontent.com/109200667/180249055-7cb2c680-c430-4881-8a7c-ad60ee628888.png)

With previous versions, it's working fine.
You can find more info about this here:
- https://stackoverflow.com/questions/67001968/how-to-disable-maven-blocking-external-http-repositories
- https://help.sonatype.com/repomanager3/nexus-repository-administration/formats/maven-repositories

My current workaround was to mirror the URL to your repository in the local `settings.xml` at the `.m2` folder.
```xml
...
  <mirrors>
    <mirror>
        <id>jsystem-mirror</id>
        <mirrorOf>jsystem</mirrorOf> <!-- Must match repository id. -->
        <name>Dummy mirror to unblock the jSystem repo</name> <!-- This is because it's using http instead of https -->
        <url>http://maven.top-q.co.il/content/groups/public</url>
    </mirror>
  </mirrors>
  <profiles>
    <profile>
      <id>artifactory</id>
      <repositories>
        <repository>
          <id>jsystem</id>
          <url>http://maven.top-q.co.il/content/groups/public</url>
        </repository>
        <repository>
...
```

I highly recommend you update your repository to support HTTPS.

**Comment by itaiag** [comment]
The repository was ported AWS hosted machine with HTTPS certification.
